# Generated by Django 4.1.1 on 2022-10-06 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='brier_content',
            new_name='brief_content',
        ),
    ]
